### ISSUE TITLE
Build error  ‘nullptr’ was not declared in this scope

### ISSUE THREAD

**Issue by idhamari** [lassoan/SlicerSegmentMesher#4]
System: Ubuntu 16

`
build/cleaver/src/lib/cleaver/Vertex.h:61:36: error: ‘nullptr’ was not declared in this scope
     Vertex(int materials) : parent(nullptr), conformedVertex(nullptr), conformedEdge(nullptr), conformedFace(nullptr),
`

and several similar errors .

I tried a suggestion to add these lines to the CMakeLists.txt but still get the same error 

`
if(UNIX)
    SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -std=gnu++0x") 
endif()
`

I was able to build the stable old version of Cleaver 2.2.1 in the system but there is no option to add its path manually when I run in cmake-gui

**Comment by lassoan** [comment]
You can set path to a custom Cleaver build in Advanced section / Custom Cleaver executable path.

**Comment by lassoan** [comment]
FYI, Linux nightly builds will be updated to use more recent gcc and cxx11 will be enabled, so most likely we'll have Segment Mesher in the extension manager in about a week.
